#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Export neovim as editor, alias n to nvim
export EDITOR=nvim
export SUDO_EDITOR=nvim
alias n=nvim
alias magit="n -c MagitOnly"

# alias firefox to firefox-developer
alias firefox=firefox-developer

# Location of user bin
export MYPATH=$HOME/bin

# Golang path variable
export GOPATH=$HOME/gocode

# Export PATH variable
export PATH=$PATH:$MYPATH:$GOPATH/bin

# Keychain
eval $(keychain --eval --quiet id_rsa)

# Node Version Manager info
export NVM_DIR="/home/nokaa/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
