#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Export neovim as editor, alias n to nvim
export EDITOR=nvim
export SUDO_EDITOR=nvim
alias n=nvim

# Force emacs to open in terminal mode
alias emacs="emacs -nw"

# Have racket REPL open with better features
# and for use with slime. Also use lang sicp
alias racket="racket -i -l xrepl -e '(require sicp)'"

# alias firefox to firefox-developer
alias firefox=firefox-developer

# Have krill load feeds by default
alias krill="krill -S ~/.krill"

# Have livestreamer use mpv as player be default
alias livestreamer="livestreamer --player mpv"

# Stack for haskell
eval "$(stack --bash-completion-script stack)"

# Transmission directories
export TRANSMISSION_DOWNLOAD_DIR=/media/Poseidon/Downloads
export TRANSMISSION_WATCH_DIR=$TRANSMISSION_DOWNLOAD_DIR/torrents

# Location of user bin
export MYPATH=$HOME/bin

# Golang path variable
export GOPATH=$HOME/gocode

# Path for rbenv
export RBENV_PATH=$HOME/.rbenv/bin

# RISCV setup
export RISCV=$HOME/Programming/git/riscv/riscv

# Export PATH variable
export PATH=$PATH:$MYPATH:$GOPATH/bin:$CABALBIN:$RBENV_PATH:$RISCV/bin

# Keychain
eval $(keychain --eval --quiet id_rsa)

# Node Version Manager info
#export NVM_DIR="/home/nokaa/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Stuff for OCaml
# OPAM configuration
. $HOME/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# rbenv
eval "$(rbenv init -)"

# List todo
task list
